language: ruby
before_install: gem install bundler -v 1.17.3
script: ./build.sh
branches:
  only:
  - master
rvm:
- 2.1.2
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
    secure: E69PKewQT2jDmwZjA5l0XpQTX+mNja/Xa5sC2HRU03BCBdtQKNSrhB7vsyFXYmov+xW63AAm+0mJsXYpSUTrjTPACENSBwzx7/kWmN5iTJ/ZlaE9q8ggK2a+n6HNHyqgw6byzc3iIhn/cFvMdlcJLYJFxj/sfmrFbNe+XfftFco7X5yMSQMSgw5i3N52JTOzJUor1TiwWJnwDiPQLeipFr0tQDzgt+63bWveHsfYxU4i6a757gddfaVzl3ZVu7YkTvDAYxX8pYIjU1YdLhnluKN8r1EWFdOdwg2O8dCfsQXuOBvrCAiYzItqa3Or36s1s3EkFxtE062xu4LzuqsCGhGDaxInMtxpjaRyKkLn0e/K9CHsoAk+uIz2FyOrhBo0pd42gzAAOeabJQ4twpqekEXH9IJxa3qkUz0AXjHT5slqgN2YB4wLei9reoRORXG4HwlOJZXtph7B6xMWJzq7sFJbwAbUjQSKuHbks9g8Xs7OUt2oWMQBJOu5n8eJqyL5+qwyUxMxg7NJeqJIR+VdFMoP9wFB1pmzmDeYU2uxod/J7Xp8rOk8K+5slogm9JXwibNRYBRvGNsbANYkNRXjssJIM8ksEHvZcnsYWALBIgll7AJhc+2ma9rG2D8bOhlRkabpqtM8uBJ3S1gobc5ESo5wGTvbumlOyyCtk4vCWnI=
